[build]
  base = "frontend"
  publish = "dist"
  command = "pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10"

[dev]
  command = "pnpm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200